apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-k8s-dev
  namespace: argocd
spec:
  project: app1-project
  source:
    repoURL: https://github.com/rm13rotem/argo_gitops.git
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
